version: '3.1'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: mypwd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      # This allows Datagrip, PgAdmin, etc. to connect to the database
      - "54321:5432"

  adminer:
    image: adminer
    ports:
        - "8080:8080"

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: