apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: ticket-app
build:
  artifacts:
  - image: us.gcr.io/ticketing-dev-306115/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
profiles:
  # Choose a profile to build locally or with GCB
  # e.g. skaffold dev -p local
  - name: local
    build:
      local:
        push: false
  - name: gcb
    build:
      googleCloudBuild:
        projectId: ticketing-dev-306115
