apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: ticket-app
build:
  # Uncomment one of these sections to determine if
  local:
    push: false
#  googleCloudBuild:
#    projectId: ticketing-dev-306115

  artifacts:
#  - image: gregbrowndev/ticking-app-auth
  - image: us.gcr.io/ticketing-dev-306115/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
