version: '3.1'

# This file is used by default by docker-compose to override the settings in the base docker-compose.yml.
# These overrides are for development, such as bind mount to /app for live code updates.

services:

  client:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      # Creates an anonymous volume to store node_modules which would get hidden within /app by the bind mount above
      - client-node_modules:/app/node_modules

volumes:
  client-node_modules:
