apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000


#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-srv
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/use-regex: 'true'
#spec:
#    rules:
#        - host: posts.com
#          http:
#            paths:
#                - path: /posts/create
#                  pathType: Prefix
#                  backend:
#                    serviceName: posts-clusterip-srv
#                    servicePort: 4000
#                - path: /posts/?(.*)/comments
#                  pathType: Prefix
#                  backend:
#                    serviceName: comments-clusterip-srv
#                    servicePort: 4001
#                - path: /posts
#                  pathType: Prefix
#                  backend:
#                    serviceName: query-clusterip-srv
#                    servicePort: 4002
#                - path: /?(.*)
#                  pathType: Prefix
#                  backend:
#                    serviceName: client-clusterip-srv
#                    servicePort: 3000
