version: '3.1'

# Compose file for production, run:
# 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml up'

# Or as a Stack
# 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml config > docker-stack.yml'
# 'docker stack deploy -c docker-stack.yml angular-reference'

services:

  client:
      ports:
       - "4250:4200"
      restart: always

