apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: ticket-app
build:
  local:
    push: false
  artifacts:
  - image: gregbrown/ticketing/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
