apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: ticket-app
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: ticketing-dev-306115
  artifacts:
  - image: us.gcr.io/ticketing-dev-306115/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
