pocd_node = { :host => "cm-template", :ip => "10.10.45.9", :box => "centos/7", :gui => false, :ram => 1024, :cpu => 4 }
varDomain = "poc-d.internal"

Vagrant.configure("2") do |config|
  config.vm.define pocd_node[:host] do |pocd_config|
    pocd_config.vm.box = pocd_node[:box]
    pocd_config.vm.network "private_network", ip: pocd_node[:ip]
    pocd_config.vm.hostname = pocd_node[:host] + "." + varDomain

    pocd_config.vm.provider :virtualbox do |v|
        v.name = pocd_node[:host].to_s
        v.gui = pocd_node[:gui]
        v.customize ["modifyvm", :id, "--memory", pocd_node[:ram].to_s]
        v.customize ["modifyvm", :id, "--cpus", pocd_node[:cpu].to_s]
    end
  end
end