apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: gregbrown/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: 'src/**/*.js'
                  dest: .
        - image: gregbrown/comments
          context: comments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: gregbrown/eventbus
          context: eventbus
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: gregbrown/moderation
          context: moderation
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: gregbrown/posts
          context: posts
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .
        - image: gregbrown/query
          context: query
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
                - src: '*.js'
                  dest: .