---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments", "replicasets", "ingresses", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
