name:                haskell-get-programming
version:             0.1.0.0
github:              "gregbrowndev/projects"
license:             BSD3
author:              "Gregory Brown"
maintainer:          "gregbrowndev@gmail.com"
copyright:           "2023 Gregory Brown"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gregbrowndev/projects/blob/master/projects/haskell-get-programming/README.md>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- split
- text
- bytestring
- filepath
- text-conversions

library:
  source-dirs: src

executables:
  haskell-get-programming-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-get-programming

tests:
  haskell-get-programming-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-get-programming
